package study.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;

@Entity
@Table(name = "users")
@Setter
@Getter
@ToString
public class User {

    /*
    NOTE 1 : @GeneratedValue(strategy = GenerationType.AUTO) 사용시 테이블 생성 불가 => H2 DB 때문일까?
    drop table user if exists
    create table user (
        id bigint not null,
        name varchar(20) not null,
        password varchar(20) not null,
        primary key (id)
    )

    NOTE 1-1 : IDENTITY 사용 시 정상 작동
    create table user (
       id bigint generated by default as identity,
        name varchar(20) not null,
        password varchar(20) not null,
        primary key (id)
    )
    TODO : 음.. MYSQL은 되나 해봐야하나
    */

    @Id
    @Column(length = 10)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    @Column(length = 20, nullable = false)
    String name;

    @Column(length = 20, nullable = false)
    String password;


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        User user = (User) o;

        if (!name.equals(user.name)) return false;
        return password.equals(user.password);
    }

    @Override
    public int hashCode() {
        int result = name.hashCode();
        result = 31 * result + password.hashCode();
        return result;
    }
}



